### ISSUE TITLE
Excel::ValueReader::XLSX::Backend::LibXML

### ISSUE THREAD

**Issue by ulibuck** [damil/Excel-ValueReader-XLSX#1]
Hi Laurent Dami
Thank you for your Excel::ValueReader::XLSX; I am using it with the LibXML back end.
It works quite well and does exactly what I want.
I came across a few points which I would like you know.
1. Date System (1904): after saving an Excel file with LibreOffice Calc I need to check for `$reader->getAttribute('date1904') eq 'true'` for the dates to work correctly.
2. Header and Footer: I am using headers and footers on my sheets. The header and footer texts are added to the last cell value. To avoid this I stop reading the sheet when the 'printOptions' node is encountered. `last if $node_name eq 'printOptions';`
3. I also found that I should add `looks_like_number $val` at two instances.

Find attached the diff file of my version to your latest 1.05 version of LibXML.pm
[diff-LibXML.txt](https://github.com/damil/Excel-ValueReader-XLSX/files/7793731/diff-LibXML.txt)
Hope this will be of help
Best regards
ulibuck

**Comment by damil** [comment]
Hi, thanks for the report.
Could you please supply an example .xlsx file that displays the problems you mentioned ? So that I can add relevant tests into the test suite.
Thanks in advance, Laurent

**Comment by ulibuck** [comment]
Hi, thanks for the fast response
Find attached an example .xlsx file that was saved by LibreOffice Calc (Version: 6.4.7.2). It has two sheets.
Running the original version 1.04 of LibXML.pm produces some warnings, wrong dates, plus a wrong value in the last cell of the second sheet.
Running my modified version 1.04 of LibXML.pm produces correct results and no warnings.
I also attach the Data::Dumper output produced by either version.
Best regards
ulibuck
[ulibuck-uli_1.04.txt](https://github.com/damil/Excel-ValueReader-XLSX/files/7794456/ulibuck-uli_1.04.txt)
[ulibuck-orig_1.04.txt](https://github.com/damil/Excel-ValueReader-XLSX/files/7794457/ulibuck-orig_1.04.txt)
[ulibuck.xlsx](https://github.com/damil/Excel-ValueReader-XLSX/files/7794458/ulibuck.xlsx)

**Comment by damil** [comment]
OK, thanks.
Fixed in v1.07 https://metacpan.org/release/DAMI/Excel-ValueReader-XLSX-1.07
