### ISSUE TITLE
Excel::ValueReader::XLSX::Backend::LibXML

### ISSUE THREAD

**Issue by ulibuck** [damil/Excel-ValueReader-XLSX#2]
Hi
Thank you for Excel::ValueReader, which is useful to me.
I came across a strange issue with Excel 365 files.
The 'sharedStrings.xml' can contain a node without any text contents like this
`<si> <t/> </si>`
Excel::ValueReader::XLSX::Backend::LibXML `sub _strings` skips such a node.
As a result the `@strings` array will be incomplete and in turn the returned array of values will be wrong.
When adding the following before line [35](https://metacpan.org/dist/Excel-ValueReader-XLSX/source/lib/Excel/ValueReader/XLSX/Backend/LibXML.pm#L35) in `sub _strings` such an empty node will not be skipped
`  elsif ($reader->isEmptyElement) {
    push @strings, '';
  }
`
Find attached an example .xlsx file that was saved by Excel 365 and contains the described issue.
[Mappe1.xlsx](https://github.com/damil/Excel-ValueReader-XLSX/files/10472040/Mappe1.xlsx)
Btw: when opening and saving the same workbook with LibreOffice Calc the issue is gone.
Hope this will be of help
Best regards
ulibuck

**Comment by ulibuck** [comment]
Additional code should be as follows in order to limit to `<t/>`
`  elsif ($node_name eq 't' and $reader->isEmptyElement) {
    push @strings, '';
  }
`
Within "RichTextRun" `<r><rPr>` there are other empty nodes which need to be skipped.

**Comment by damil** [comment]
Hi Ulibuck,
Thanks for the report and for the test file.
Fixed in v1.09. Your proposed solution did break other test cases, so I solved it in a slightly different way.
Best regards, Laurent

**Comment by damil** [comment]
Just for my curiosity : is there any particular reason why you use the LibXML backend instead of the Regex backend ?
